### ISSUE TITLE
CUDA_ERROR_NOT_FOUND: "named symbol not found" on Tesla T4 with CUDA 12.1

### ISSUE THREAD

**Issue by mmhanda** [kyutai-labs/moshi#355]
### Backend impacted

The Rust implementation

### Operating system

Linux

### Hardware

GPU with CUDA

### Description

Hello,

I am encountering a persistent CUDA_ERROR_NOT_FOUND error when trying to run moshi-server after building from source. The error occurs during the ASR model warm-up phase.

I have followed an extensive debugging process, including a clean rebuild with the compute capability explicitly set for my GPU, but the error remains. This suggests a potential issue within the Candle build process for this specific architecture.

System Information:

GPU: Tesla T4

CUDA Toolkit Version (from nvcc --version): 12.1

NVIDIA Driver Version (from nvidia-smi): 535.261.03

OS (uname -a): [Paste your uname -a output here]

Final Error Log:

The error occurs after successfully building from the main branch and running the binary. The full log is below:

### Extra information

(unmute) ➜  moshi-server git:(main) ✗ echo "### Starting Final Fix: Cleaning and Rebuilding with forced GPU architecture... ###"

# Ensure we are in the correct directory
cd ~/moshi-src/rust/moshi-server

# 1. Clean all previous build artifacts
echo ">>> Cleaning previous build..."
cargo clean

# 2. Rebuild the server using the configuration in .cargo/config.toml
echo ">>> Rebuilding... (This will take several minutes)"
CARGO_TARGET_DIR=target CUDA_LAUNCH_BLOCKING=1 cargo build --release --features cuda

echo
echo ">>> Build finished."
echo "### Attempting to run the newly built server... ###"

# 3. Run the new binary
CONFIG_PATH="/home/umute/unmute/services/moshi-server/configs/stt.toml"
./target/release/moshi-server worker --config "$CONFIG_PATH" --port 8092
### Starting Final Fix: Cleaning and Rebuilding with forced GPU architecture... ###
>>> Cleaning previous build...
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/umute/moshi-src/rust/moshi-backend/Cargo.toml
workspace: /home/umute/moshi-src/rust/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/umute/moshi-src/rust/moshi-cli/Cargo.toml
workspace: /home/umute/moshi-src/rust/Cargo.toml
     Removed 0 files
>>> Rebuilding... (This will take several minutes)
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/umute/moshi-src/rust/moshi-backend/Cargo.toml
workspace: /home/umute/moshi-src/rust/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/umute/moshi-src/rust/moshi-cli/Cargo.toml
workspace: /home/umute/moshi-src/rust/Cargo.toml
warning: hiding a lifetime that's elided elsewhere is confusing
  --> moshi-server/src/tts_preprocess.rs:15:26
   |
15 | fn parse_segments(input: &str) -> Vec<Segment> {
   |                          ^^^^         ------- the same lifetime is hidden here
   |                          |
   |                          the lifetime is elided here
   |
   = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
   = note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
   |
15 | fn parse_segments(input: &str) -> Vec<Segment<'_>> {
   |                                              ++++

warning: `moshi-server` (bin "moshi-server") generated 1 warning
    Finished `release` profile [optimized + debuginfo] target(s) in 0.27s

>>> Build finished.
### Attempting to run the newly built server... ###
2025-08-10T07:35:48.732020Z  INFO moshi_server: moshi-server/src/main.rs:469: build_info=BuildInfo { build_timestamp: "2025-08-10T07:16:54.205083242Z", build_date: "2025-08-10", git_branch: "main", git_timestamp: "2025-08-04T08:49:52.000000000+02:00", git_date: "2025-08-04", git_hash: "f2573439ed70a8384b3f390e561f9c325fc890c7", git_describe: "f257343", rustc_host_triple: "x86_64-unknown-linux-gnu", rustc_version: "1.89.0", cargo_target_triple: "x86_64-unknown-linux-gnu" }
2025-08-10T07:35:48.732043Z  INFO moshi_server: moshi-server/src/main.rs:543: starting worker num_workers=4
2025-08-10T07:35:50.321383Z  INFO moshi_server: moshi-server/src/main.rs:570: listening on http://0.0.0.0:8092
2025-08-10T07:35:50.321384Z  INFO moshi_server::batched_asr: moshi-server/src/batched_asr.rs:226: warming-up the asr
2025-08-10T07:35:50.752154Z ERROR moshi_server::utils: moshi-server/src/utils.rs:199: task failed name="model_loop" err=DriverError(CUDA_ERROR_NOT_FOUND, "named symbol not found")
   0: candle_core::error::Error::bt
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/error.rs:255:25
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/error.rs:60:65
   2: core::result::Result<T,E>::map_err
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/result.rs:914:27
   3: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/error.rs:60:14
   4: candle_core::cuda_backend::device::CudaDevice::get_or_load_func
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/device.rs:219:51
   5: <candle_core::cuda_backend::IndexSelect as candle_core::cuda_backend::utils::Map1>::f
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/mod.rs:432:24
   6: candle_core::cuda_backend::utils::Map1::map
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/utils.rs:23:40
   7: <candle_core::cuda_backend::CudaStorage as candle_core::backend::BackendStorage>::index_select
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/cuda_backend/mod.rs:1893:50
   8: candle_core::storage::Storage::index_select
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/storage.rs:725:35
   9: candle_core::tensor::Tensor::index_select
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/tensor.rs:1654:38
  10: <candle_nn::embedding::Embedding as candle_core::Module>::forward
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-nn-0.9.1/src/embedding.rs:33:38
  11: <moshi::nn::MaybeQuantizedEmbedding as candle_core::Module>::forward
             at /home/umute/moshi-src/rust/moshi-core/src/nn.rs:162:42
  12: candle_core::tensor::Tensor::apply
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/candle-core-0.9.1/src/tensor.rs:2476:11
  13: moshi::lm::LmModel::forward_cond
             at /home/umute/moshi-src/rust/moshi-core/src/lm.rs:879:40
  14: moshi::asr::State::step_tokens
             at /home/umute/moshi-src/rust/moshi-core/src/asr.rs:193:25
  15: moshi::asr::State::step_pcm
             at /home/umute/moshi-src/rust/moshi-core/src/asr.rs:132:18
  16: moshi_server::batched_asr::warmup
             at ./src/batched_asr.rs:181:31
  17: moshi_server::batched_asr::BatchedAsrInner::start_model_loop::{{closure}}
             at ./src/batched_asr.rs:227:13
  18: moshi_server::utils::spawn_blocking::{{closure}}
             at ./src/utils.rs:197:47
  19: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/task.rs:42:21
  20: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:331:24
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/loom/std/unsafe_cell.rs:16:9
  22: tokio::runtime::task::core::Core<T,S>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:320:30
  23: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:532:30
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panic/unwind_safe.rs:272:9
  25: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  26: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  27: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  28: tokio::runtime::task::harness::poll_future
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
  29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
  30: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:20
  31: tokio::runtime::task::raw::RawTask::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
  32: tokio::runtime::task::UnownedTask<S>::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:500:13
  33: tokio::runtime::blocking::pool::Task::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:161:19
  34: tokio::runtime::blocking::pool::Inner::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:511:22
  35: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:469:47
  36: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:152:18
  37: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/mod.rs:559:17
  38: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panic/unwind_safe.rs:272:9
  39: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  40: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  41: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  42: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/mod.rs:557:30
  43: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:250:5
  44: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1966:9
  45: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/pal/unix/thread.rs:107:17
  46: <unknown>
  47: <unknown>

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.98/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/result.rs:2079:27
   2: moshi_server::batched_asr::warmup
             at ./src/batched_asr.rs:181:25
   3: moshi_server::batched_asr::BatchedAsrInner::start_model_loop::{{closure}}
             at ./src/batched_asr.rs:227:13
   4: moshi_server::utils::spawn_blocking::{{closure}}
             at ./src/utils.rs:197:47
   5: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/task.rs:42:21
   6: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:331:24
   7: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/loom/std/unsafe_cell.rs:16:9
   8: tokio::runtime::task::core::Core<T,S>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/core.rs:320:30
   9: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:532:30
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panic/unwind_safe.rs:272:9
  11: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  12: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  13: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  14: tokio::runtime::task::harness::poll_future
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:520:18
  15: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:209:27
  16: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/harness.rs:154:20
  17: tokio::runtime::task::raw::RawTask::poll
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/raw.rs:201:18
  18: tokio::runtime::task::UnownedTask<S>::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/task/mod.rs:500:13
  19: tokio::runtime::blocking::pool::Task::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:161:19
  20: tokio::runtime::blocking::pool::Inner::run
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:511:22
  21: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/umute/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/runtime/blocking/pool.rs:469:47
  22: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/backtrace.rs:152:18
  23: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/mod.rs:559:17
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panic/unwind_safe.rs:272:9
  25: std::panicking::catch_unwind::do_call
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:589:40
  26: std::panicking::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:552:19
  27: std::panic::catch_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panic.rs:359:14
  28: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/thread/mod.rs:557:30
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/ops/function.rs:250:5
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/alloc/src/boxed.rs:1966:9
  31: std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/sys/pal/unix/thread.rs:107:17
  32: <unknown>
  33: <unknown>
^C

### Environment

System Information
Operating system version: Ubuntu 22.04.5 LTS

Python version: 3.12.8

PyTorch version: PyTorch is not installed in this environment.

CUDA version (from PyTorch): PyTorch is not installed in this environment.

GPU model and memory: Tesla T4, 16384MiB

CUDA Toolkit Version (from nvcc --version): 12.1

NVIDIA Driver Version (from nvidia-smi): 535.261.03

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

Sun Aug 10 07:43:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.65.06              Driver Version: 580.65.06      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       On  |   00000001:00:00.0 Off |                  Off |
| N/A   38C    P0             28W /   70W |       0MiB /  16384MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

**Comment by mmhanda** [comment]
i fixed it the problem is with the moshi-server, i did a custom build to and replaced any place where using bf16 with f16, because the Tesla T4 does not support bf16, i think i will push the new version of umute with all the fixes 


<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/75769f09-864e-48f2-add8-0c3b3a17424b" />

**Comment by jo-jstrm** [comment]
Impressive, thanks for debugging and sharing your insights!

Our short term solution is to switch GPUs. But if the fix is "only" the float-types, maybe the kyutai folks would be interested in a pull request.
